# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: addeda75a04a2fd346a9df69366d46f1c317999cfb8d361e1da0c0c5aa88c9c9640fc9bd04b29a9d12dff6ca367ea4d451d4439e2f1bd4a692905575c9753ff7

test:
  secret_key_base: a0bf8fb9fed2b6f98399975fca3e816a2bc6a4ce49e2461dce84cd491401be32b1399086752aa19021089baa1ff086549182e74333c4a9ef4a212f12ec4686f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
